export const projectsData = [
  {
    id: 1,
    image: '/images/tamtu.png',
    title: 'Tamtu city games - admin panel',
    text: 'Przy tworzeniu panelu zarządzania, byłem odpowiedzialny za część dotyczącą użytkowników.',
    tech: [
      'typescript',
      'react',
      'react router',
      'react query',
      'react hook forms',
      'MaterialUI',
      'Tailwind',
      'Axios',
      'Postman',
    ],
  },
  {
    id: 2,
    image: '/images/tamtu.png',
    title: 'Tamtu city games - webpage',
    text: 'Przy tworzeniu panelu zarządzania, byłem odpowiedzialny za część dotyczącą użytkowników.',
    tech: [
      'next.js',
      'typescript',
      'react hook forms',
      'tailwind',
      'axios',
      'graphQL',
      'postman',
      'directus',
    ],
  },
  {
    id: 3,
    image: '/images/furgonetka.png',
    title: 'Portmonetka - wtyczka checkout',
    text: 'Samodzielnie stworzyłem MVP Front-endu',
    tech: ['react', 'react router', 'Styled components'],
  },
  {
    id: 4,
    image: '/images/skydental.png',
    title: 'Skydental - webpage',
    text: 'Samodzielnie wykonałem stronę ',
    tech: [
      'next',
      'typescript',
      'react query',
      'Styled components',
      'GraphQL',
      'Directus',
      'framer motion',
    ],
  },
  {
    id: 5,
    image: '/images/brainforge.png',
    title: 'BrainforgeIT - webpage',
    text: 'Strona wykonana wspólnie ',
    tech: [
      'next.js',
      'typescript',
      'react query',
      'Styled components',
      'GraphQL',
      'Directus',
      'framer motion',
    ],
  },
  {
    id: 6,
    image: '/images/prete.png',
    title: 'Prete - e-commerce',
    text: 'sklep z biżuterią',
    tech: [
      'next.js',
      'typescript',
      'react query',
      'Styled components',
      'GraphQL',
      'Vendure',
    ],
  },
  {
    id: 7,
    image: '/images/panele.png',
    title: 'Hurtownia fotowoltaiczna',
    text: 'Przejąłem gotowy projekt. Zajmowałem się naprawą błędów oraz rozwijałem nowe funkcjonalności zarówno na frontendzie jak i backendzie',
    tech: ['vue', 'vuex', 'Axios', 'Vuetify', 'node'],
  },
  {
    id: 8,
    image: '/images/panele-montaz.png',
    title: 'Panel zarządzania pracami wykonawczymi',
    text: 'Przejąłem projekt w trakcie tworzenia. Zajmowałem się dokończeniem projektu zarówno na frontendzie jak i backendzie',
    tech: ['vue', 'vuex', 'Axios', 'Vuetify', 'node', 'typescript'],
  },
  {
    id: 9,
    image: '/images/tixe.png',
    title: 'Tixe-Wash - admin panel',
    text: 'Przy tworzeniu panelu zarządzania, byłem odpowiedzialny za część dotyczącą użytkowników.',
    tech: ['next', 'MaterialUI', 'react query', 'Tailwind'],
  },
];
